In [ ]:
pip install eif  #pip Installing the Extended Isolation Forest.

Requirement already satisfied: eif in /usr/local/lib/python3.7/dist-packages (2.0.2)
Requirement already satisfied: cython in /usr/local/lib/python3.7/dist-packages (from eif) (0.29.24)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from eif) (1.19.5)

In [ ]:
import pandas as pd   #importing pandas
import numpy as np    #importing numpy
import seaborn as sns #importing seaborn
import matplotlib.pyplot as plt   #importing matplotlib
import eif as iso     #importing extended isolation forest
from sklearn.ensemble import IsolationForest   #importing Isolation Forest
from sklearn.model_selection import train_test_split  #importing train nd test split  
import warnings
warnings.filterwarnings("ignore")

## IsolationForest

isolation forest with predefined parameters

In [ ]:
df=pd.read_csv('/content/winequality-white.csv')

In [ ]:
model = IsolationForest() #giving a variable to Isoaltionforest
model.fit(df)   #fiting the dataframe
pred_test = model.predict(df)  #predicting the outliers(-1 are outliers and 1 are normal data points)

In [ ]:
decision_score=model.decision_function(df) #It returns a score with high negative score are more anomalous
decision_score

array([0.01967468, 0.10416122, 0.09160898, ..., 0.08807858, 0.04153049,
       0.04889149])

In [ ]:
df['pred_test']=pred_test

In [ ]:
df['decision_score']=decision_score

In [ ]:
df[df['pred_test']==-1]  #checking only outliers

      fixed acidity  volatile acidity  ...  pred_test  decision_score
14              8.3              0.42  ...         -1       -0.052545
17              6.2              0.66  ...         -1       -0.051887
20              6.2              0.66  ...         -1       -0.051887
23              7.6              0.67  ...         -1       -0.016223
54              6.8              0.20  ...         -1       -0.007590
...             ...               ...  ...        ...             ...
4867            5.3              0.60  ...         -1       -0.025433
4877            5.9              0.54  ...         -1       -0.030131
4878            6.2              0.53  ...         -1       -0.032819
4883            4.9              0.47  ...         -1       -0.014064
4887            6.2              0.41  ...         -1       -0.048734

[399 rows x 14 columns]

--------------------------------------------------------------------------

Isoaltionforest with  parameters

In [ ]:
df=pd.read_csv('/content/winequality-white.csv')

In [ ]:
#giving a variable to Isoaltionforest with parameters
model = IsolationForest(n_estimators=100, max_samples=256, contamination=0.2,random_state=42)
model.fit(df)  #fiting the dataframe
pred_test = model.predict(df) #predicting the outliers(-1 are outliers and 1 are normal data points)

In [ ]:
decision_score=model.decision_function(df) #It returns a score with high negative score are more anomalous

In [ ]:
df['pred_test']=pred_test
df['decision_score']=decision_score
df[df['pred_test']==-1]  #checking only outliers

      fixed acidity  volatile acidity  ...  pred_test  decision_score
0               7.0              0.27  ...         -1       -0.013886
7               7.0              0.27  ...         -1       -0.013886
14              8.3              0.42  ...         -1       -0.075059
17              6.2              0.66  ...         -1       -0.062195
20              6.2              0.66  ...         -1       -0.062195
...             ...               ...  ...        ...             ...
4877            5.9              0.54  ...         -1       -0.053817
4878            6.2              0.53  ...         -1       -0.052312
4883            4.9              0.47  ...         -1       -0.019904
4886            6.2              0.21  ...         -1       -0.027266
4887            6.2              0.41  ...         -1       -0.096053

[980 rows x 14 columns]

-------------------------------------------------------

Extended Isolation Forest

In [ ]:
df1=pd.read_csv('/content/winequality-white.csv') #reading the dataset

ExtensionLevel decides what level of extension to be used

if ExtensionLevel == 0 nothing but isolation forest

ifExtensionLevel == no of features -1 ,called extended isolation forest

In [ ]:
model1=iso.iForest(df1.values,ntrees=100, sample_size=500, ExtensionLevel=0) #if 
model2=iso.iForest(df1.values,ntrees=100, sample_size=500, ExtensionLevel=df1.shape[1]-1) #EIf

In [ ]:
model1.compute_paths(df1.values)  #gives anomaly score for if

array([0.49288104, 0.38089102, 0.38338395, ..., 0.40325785, 0.43822846,
       0.42005078])

In [ ]:
model2.compute_paths(df1.values)  #gives anomaly score for Eif

array([0.44185447, 0.42202552, 0.41282663, ..., 0.39166462, 0.40430307,
       0.4016189 ])

In [ ]:
pred_class1=np.where(model1.compute_paths(df1.values)>0.55,1,0)  #converting the values to 1 which are more than .55 and 0 which are less than
pred_class2=np.where(model2.compute_paths(df1.values)>0.55,1,0)  #converting the values to 1 which are more than .55 and 0 which are less than

In [ ]:
pred_class1 # Outliers for If

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
pred_class2  # Outliers for EIf

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
df1['pred_class1']=pred_class1  # Outliers for If
df1['pred_class2']=pred_class2  # Outliers for EIf

In [ ]:
df1[df1['pred_class1']==1]  # checking only outliers if

      fixed acidity  volatile acidity  ...  pred_class1  pred_class2
115             5.5             0.485  ...            1            0
178             6.0             0.670  ...            1            0
294             9.1             0.590  ...            1            0
687             6.8             0.670  ...            1            0
873            10.3             0.170  ...            1            1
1034            7.9             0.640  ...            1            0
1217            8.0             0.610  ...            1            1
1245            8.0             0.660  ...            1            1
1304            8.0             0.590  ...            1            0
1417            8.6             0.550  ...            1            1
1436            8.5             0.560  ...            1            1
1608            6.9             0.270  ...            1            1
1638            7.6             0.470  ...            1            0
1688            6.7             0.250  ...            1            1
1835            8.0             0.550  ...            1            0
1848            8.7             0.490  ...            1            1
1856           10.0             0.910  ...            1            0
1931            7.1             0.490  ...            1            1
1951            9.9             1.005  ...            1            0
2050           11.8             0.230  ...            1            0
2154            9.8             0.930  ...            1            0
2321            4.6             0.445  ...            1            0
2378            9.4             0.230  ...            1            1
2668            9.6             0.655  ...            1            0
2781            7.8             0.965  ...            1            1
2872            4.2             0.170  ...            1            1
3152            7.6             0.250  ...            1            1
3220            9.0             0.380  ...            1            0
3307            9.4             0.240  ...            1            1
3710            4.7             0.670  ...            1            1
3773            5.0             0.610  ...            1            1
3901            4.8             0.650  ...            1            1
4480            5.9             0.220  ...            1            0
4745            6.1             0.260  ...            1            1
4792            4.7             0.785  ...            1            0
4815            6.2             0.760  ...            1            0

[36 rows x 14 columns]

In [ ]:
df1[df1['pred_class2']==1]   # checking only outliers for Eif

      fixed acidity  volatile acidity  ...  pred_class1  pred_class2
25              7.0             0.250  ...            0            1
31              8.3             0.140  ...            0            1
70              6.2             0.270  ...            0            1
71              6.8             0.300  ...            0            1
91              6.1             0.270  ...            0            1
...             ...               ...  ...          ...          ...
4648            6.7             0.610  ...            0            1
4681            5.6             0.270  ...            0            1
4745            6.1             0.260  ...            1            1
4839            5.2             0.405  ...            0            1
4841            5.7             0.220  ...            0            1

[195 rows x 14 columns]